### ISSUE TITLE
Max number of results per corpus

### ISSUE THREAD

**Issue by tommv** [nbonfils/bibliograph2#1]
It is indeed crucial to have a maximum limit on the number of results per corpus, but it would be nice to
1. let the user choose where to place the limit - within a "reasonable range" - while explaining that this has consequences on the computation time. The "reasonable range" should be fixed by considering the minimum amount of data necessary to obtain an interesting network and the maximum amount allowing to have a working and fluid computation.
2. order documents by number of citations and cut the corpus while keeping records with the most citations.

**Comment by nbonfils** [comment]
Agreed.
1. we can have an input box on the first "search" step that allows the user to specify the maximum amount of works being searched. I could imagine putting a **default of 10'000 entries** and allowing up to a **maximum of 100'000 entries**. Of course we can tweak those numbers based on performance. The message to the used could be something like "Fetch a corpus of up to **X** most cited works" where **X** is the input field.
2. Is already implemented: fbe0787f6fb052f3532c5b6694d1e2a8e5520a0f and 454b48f5f494d4b4dde2d963127d50bd3059c2d0

**Comment by tommv** [comment]
Solved, thanks!
