### ISSUE TITLE
Sizing and coloring nodes

### ISSUE THREAD

**Issue by tommv** [nbonfils/bibliograph2#6]
In the GEXF created by the Bibliograph,
- Nodes should be colored and categorized according to their type (references, records, authors, insitutions...)
- Nodes should be sized by number of records in which they appear, but with a size that "normalized" by category = in each category the node with most appearances should have a size of 100 and the node with the least  appearances a size of 1.

**Comment by nbonfils** [comment]
I normalized the size of the nodes to be capped at **30 for refs** and **50 for metadata**.

It currently looks like this:
![gephi_nodesize](https://github.com/nbonfils/bibliograph2/assets/14347927/cb04e916-0ce2-4c16-856e-5164bfe5fce8)
